# Generated by Django 4.1.2 on 2022-10-21 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_pub_data_question_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_test',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='voter',
            new_name='votes',
        ),
    ]
